"""initial schema

Revision ID: 29b258f63239
Revises: 
Create Date: 2026-06-10 16:17:08.618272

"""
from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '29b258f63239'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('app_state',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('saved_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('media_pk', sa.Text(), nullable=False),
    sa.Column('media_type', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=8), nullable=False),
    sa.Column('instagram_url', sa.Text(), nullable=True),
    sa.Column('author_username', sa.Text(), nullable=True),
    sa.Column('author_full_name', sa.Text(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('hashtags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('post_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('saved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=True),
    sa.Column('category_confidence', sa.Float(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('transcript_segments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('transcript_lang', sa.String(length=8), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('error_log', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_items_category'), 'saved_items', ['category'], unique=False)
    op.create_index('ix_saved_items_ingested_at', 'saved_items', [sa.literal_column('ingested_at DESC')], unique=False)
    op.create_index(op.f('ix_saved_items_media_pk'), 'saved_items', ['media_pk'], unique=True)
    op.create_index(op.f('ix_saved_items_status'), 'saved_items', ['status'], unique=False)
    op.create_table('embeddings',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('vector', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['saved_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('extractions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('schema_version', sa.String(length=8), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['saved_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id')
    )
    op.create_table('llm_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=True),
    sa.Column('stage', sa.String(length=16), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('input_tokens', sa.BigInteger(), nullable=False),
    sa.Column('output_tokens', sa.BigInteger(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['saved_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_refs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('s3_key', sa.Text(), nullable=False),
    sa.Column('media_kind', sa.String(length=16), nullable=False),
    sa.Column('bytes', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['saved_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute(
        "CREATE INDEX ix_embeddings_vector_cosine ON embeddings "
        "USING ivfflat (vector vector_cosine_ops) WITH (lists = 100)"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media_refs')
    op.drop_table('llm_usage')
    op.drop_table('extractions')
    op.drop_table('embeddings')
    op.drop_index(op.f('ix_saved_items_status'), table_name='saved_items')
    op.drop_index(op.f('ix_saved_items_media_pk'), table_name='saved_items')
    op.drop_index('ix_saved_items_ingested_at', table_name='saved_items')
    op.drop_index(op.f('ix_saved_items_category'), table_name='saved_items')
    op.drop_table('saved_items')
    op.drop_table('app_state')
    # ### end Alembic commands ###
