"""v2 transcript provider, resources, engagements

Revision ID: 56bbf504f257
Revises: 29b258f63239
Create Date: 2026-06-10 17:45:14.847514

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '56bbf504f257'
down_revision: str | None = '29b258f63239'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engagements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('creator_username', sa.Text(), nullable=True),
    sa.Column('creator_user_id', sa.Text(), nullable=True),
    sa.Column('media_pk', sa.Text(), nullable=False),
    sa.Column('keyword', sa.Text(), nullable=False),
    sa.Column('needs_follow', sa.Boolean(), nullable=False),
    sa.Column('channel', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.BigInteger(), nullable=False),
    sa.Column('commented_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dm_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resource_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['saved_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id')
    )
    op.create_index(op.f('ix_engagements_status'), 'engagements', ['status'], unique=False)
    op.add_column('saved_items', sa.Column('transcript_provider', sa.String(length=16), nullable=True))
    op.add_column('saved_items', sa.Column('resources', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saved_items', 'resources')
    op.drop_column('saved_items', 'transcript_provider')
    op.drop_index(op.f('ix_engagements_status'), table_name='engagements')
    op.drop_table('engagements')
    # ### end Alembic commands ###
